# VYTAL/docker-compose.yml

services:
  # 1. The React Frontend Service
  frontend:
    container_name: vytal-frontend
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-node

  # 2. The Node.js Backend Service (API Gateway)
  backend-node:
    container_name: vytal-backend-node
    build:
      context: ./backend-node
    ports:
      - "8080:8080"
    depends_on:
      - backend-python

  # 3. The Python AI Service
  backend-python:
    container_name: vytal-backend-python
    build:
      context: ./backend-python
    env_file:
      - ./backend-python/.env