# VYTAL/docker-compose.yml

version: '3.8'

services:
  # 1. The React Frontend Service
  frontend:
    container_name: vytal-frontend
    build:
      context: ./frontend
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx)
    depends_on:
      - backend-node # Don't start until the Node backend is ready

  # 2. The Node.js Backend Service (API Gateway)
  backend-node:
    container_name: vytal-backend-node
    build:
      context: ./backend-node
    ports:
      - "8080:8080" # Map host port 8080 to container port 8080
    depends_on:
      - backend-python # Don't start until the Python AI service is ready

  # 3. The Python AI Service
  backend-python:
    container_name: vytal-backend-python
    build:
      context: ./backend-python
    env_file:
      - ./backend-python/.env # Load API keys from the .env file